// export const UPLOAD_IMAGES = 'UPLOAD_IMAGES';
// export const UPLOAD_IMAGES_SUCCESS = 'UPLOAD_IMAGES_SUCCESS';
// export const UPLOAD_IMAGES_FAILURE = 'UPLOAD_IMAGES_FAILURE';

// export const UPLOAD_TEXT_FIELDS = 'UPLOAD_TEXT_FIELDS';
// export const UPLOAD_TEXT_FIELDS_SUCCESS = 'UPLOAD_TEXT_FIELDS_SUCCESS';
// export const UPLOAD_TEXT_FIELDS_FAILURE = 'UPLOAD_TEXT_FIELDS_FAILURE';

export const INPUT_FIELDS = 'INPUT_FIELDS';
export const IMAGE_FILES = 'IMAGE_FILES';